version: "3"

services:
  webserver:
    image: node:boron
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - ./client:/app
    command: bash -c "npm install && npm start"

  api:
    image: node:boron
    links:
      - mongodb
      - rabbitmq
    ports:
      - 8080:8080
      - 8081:8081
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "npm install && npm start"
  
  runners:
    build: ./runner
    links:
      - rabbitmq
    depends_on:
      - api
    working_dir: /app
    volumes:
      - ./runner:/app
    command: bash -c "pip install -r requirements.txt && npm install && npm start"

  rabbitmq:
    image: rabbitmq:3.6
    ports:
      - 5672:5672
      
  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
    command: /bin/sh -c "mongod --smallfiles"
